Change to use kernel-slim image
OpenLiberty/draft-guide-operators-openshift pull request #123
Opened 2023-06-22 19:38 UTC by gkwan-ibm

Address issue OpenLiberty/guides-common/issues/861

2023-07-12 13:29 UTC, jakub-pomykala commented on README.adoc
> +If your cluster does not install the https://cert-manager.io[cert-manager^] yet, install it by running the following command that refers to the official https://cert-manager.io/docs/installation[cert
This doesn't make sense recommend:

```suggestion
If your cluster has not installed the https://cert-manager.io[cert-manager^] yet, install it by running the following command that refers to the official https://cert-manager.io/docs/installation[cert-manager installation] documentation:
```

2023-07-13 08:02 UTC, jakub-pomykala approved these changes
LGTM

2023-07-18 13:41 UTC, dmuelle requested changes
ID review

2023-07-18 13:41 UTC, dmuelle commented on README.adoc
> +If your cluster has not installed the https://cert-manager.io[cert-manager^] yet, install it by running the following command that refers to the official https://cert-manager.io/docs/installation[cer
```suggestion
If the https://cert-manager.io[cert-manager^]  is not installed on your cluster yet, install it by running the following command:
```

2023-07-18 13:41 UTC, dmuelle commented on README.adoc
> +
```suggestion
For more information, see the https://cert-manager.io/docs/installation[cert-manager installation] documentation.
```

2023-07-18 14:34 UTC, dmuelle approved these changes
LGTM, thanks

2023-07-18 20:30 UTC, merged